const container = document.querySelector('#container');
const content = document.createElement('div');
const pElement = document.createElement('p');
const h3Element = document.createElement('h3');
const pinkConteiner = document.createElement('div');
const pinkElement = document.createElement('p');
const h1ElementPink = document.createElement('h3');
pinkElement.textContent = 'I’m in a div';
h1ElementPink.textContent= 'ME TOO!';
pinkConteiner.style.backgroundColor = 'pink'; 
pinkConteiner.style.borderColor = 'black';
pinkConteiner.style.borderWidth = '10px';
h3Element.style.color = 'blue';
h3Element.textContent = 'I’m a blue h3!';
pElement.style.color = 'red';
pElement.textContent = 'Hey I’m red!';
content.classList.add('content');
content.textContent = 'This is the glorious text-content!';
container.appendChild(content);
container.appendChild(pElement);
container.appendChild(h3Element);
container.appendChild(pinkConteiner);
pinkConteiner.appendChild(pinkElement);
pinkConteiner.appendChild(h1ElementPink);
